name: levitasync
description: LevitaSync - App completo para ministérios de louvor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.2
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.2.2

  # Security
  crypto: ^3.0.3

  # UI
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.1

  # Utils
  url_launcher: ^6.2.2
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
